sudo: required
dist: xenial


install:
  - sudo apt-get install -y --force-yes gdnsd

before_script:
  - sudo curl https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz --resolve 'geolite.maxmind.com:443:104.16.37.47' --output ~/GeoLite2-Country.tar.gz
  - sudo cp config /etc/gdnsd/
  - sudo cp admin_state /etc/gdnsd/
  - sudo cp zones/* /etc/gdnsd/zones/
  - cat ~/GeoLite2-Country.tar.gz
  - gunzip ~/GeoLite2-Country.tar.gz
  - tar -xvf ~/GeoLite2-Country.tar
  - sudo mkdir -p /usr/share/GeoIP
  - sudo cp ~/GeoLite2-Country_*/GeoLite2-Country.mmdb /usr/share/GeoIP/GeoLite2-Country.mmdb

script:
  - sudo gdnsd checkconf

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} 
%{message} %{build_url}"
  email:
    recipients:
      - southparkfan@miraheze.org
    on_success: change
    on_failure: always
